{
  "formatVersion": "1.1",
  "component": {
    "group": "ASMDemo",
    "module": "privacy-plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.didiglobal.booster",
          "module": "booster-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-transform-asm",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "privacy-1.0.0.jar",
          "url": "privacy-1.0.0.jar",
          "size": 68827,
          "sha512": "d414af0acd9557513a74495216f2493d50b80ea687e920e0ee771302fc457f83ed6525d224638280774761918aae2515e0ea1ebfa911f0eebeef3bb07884b954",
          "sha256": "84905081ecb8a000b04103bd24f7c255e3ec97ae1edf30d1f120566961744012",
          "sha1": "0f89578b2eb5644154ef444aeea2a9e506a57dc8",
          "md5": "a30d557ed5bcee57cc4c78ede71ec4c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-transform-asm",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "privacy-1.0.0.jar",
          "url": "privacy-1.0.0.jar",
          "size": 68827,
          "sha512": "d414af0acd9557513a74495216f2493d50b80ea687e920e0ee771302fc457f83ed6525d224638280774761918aae2515e0ea1ebfa911f0eebeef3bb07884b954",
          "sha256": "84905081ecb8a000b04103bd24f7c255e3ec97ae1edf30d1f120566961744012",
          "sha1": "0f89578b2eb5644154ef444aeea2a9e506a57dc8",
          "md5": "a30d557ed5bcee57cc4c78ede71ec4c3"
        }
      ]
    }
  ]
}
